name: java workflow
on:
- push
jobs:
  Run-Java-Code:
    runs_on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
    - run: javac HelloWorld.java
    - run: java HelloWorld
