name: java workflow
on:
- push
jobs:
  Run-Java-Code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.25
    - name: Verify Terraform version
      run: terraform --version
    - run: javac HelloWorld.java
    - run: java HelloWorld
